// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCESOsbMXY-a0eyS20ev3TwXYTwiEQ4VP0',
    appId: '1:883967419787:web:33e014f05076c0c38fbb8e',
    messagingSenderId: '883967419787',
    projectId: 'smarthomedevices-5316a',
    authDomain: 'smarthomedevices-5316a.firebaseapp.com',
    storageBucket: 'smarthomedevices-5316a.firebasestorage.app',
    measurementId: 'G-78KT6RP1BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd3r2LbCB5k5dKFmKkShI_j9Vdn3d7I9M',
    appId: '1:883967419787:android:0c272919fdac5f8c8fbb8e',
    messagingSenderId: '883967419787',
    projectId: 'smarthomedevices-5316a',
    storageBucket: 'smarthomedevices-5316a.firebasestorage.app',
  );

}